[package]
name = "eMARS"
version = "0.1.0"
edition = "2021"

[dependencies]
corewars = "0.2.0"
corewars-core = "0.2.0"
corewars-parser = "0.2.0"
egui = "0.21.0"
egui-macroquad = "0.15.0"
macroquad = { version = "0.3.26", default-features = false }
rand = "0.9.1"
